name: Trigger AWS CodePipeline

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.1.0
        with:
          aws-region: "ap-southeast-1"
          aws-access-key: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.ACCESS_KEY_SECRETS }}
          pipeline-name: "ecr-pipeline"
